import { describe, expect, it, vi } from "vitest";
import { CaptureProtectionManager, affinityName, applyCaptureProtection, getCaptureProtectionCapabilities, type CaptureProtectionWindowLike } from "./overlay-capture-protection";
function makeWindow(protectedValue = true): CaptureProtectionWindowLike & { setContentProtection: ReturnType<typeof vi.fn>; hide: ReturnType<typeof vi.fn> } {
  return { isDestroyed: () => false, setContentProtection: vi.fn(), isContentProtected: vi.fn(() => protectedValue), hide: vi.fn(), getNativeWindowHandle: () => Buffer.alloc(8) };
}
const modern = getCaptureProtectionCapabilities("win32", "10.0.22631");
const old = getCaptureProtectionCapabilities("win32", "10.0.18363");
const native = (name: "WDA_EXCLUDEFROMCAPTURE" | "WDA_MONITOR" = "WDA_EXCLUDEFROMCAPTURE") => () => ({ ok: true, affinity: name === "WDA_EXCLUDEFROMCAPTURE" ? 0x11 : 1, affinityName: name });
describe("capture protection V3", () => {
  it("maps affinity values", () => expect([affinityName(0), affinityName(1), affinityName(0x11), affinityName(7)]).toEqual(["WDA_NONE", "WDA_MONITOR", "WDA_EXCLUDEFROMCAPTURE", "UNKNOWN"]));
  it("maps Windows builds", () => { expect(modern.requestedAffinity).toBe("WDA_EXCLUDEFROMCAPTURE"); expect(old.requestedAffinity).toBe("WDA_MONITOR"); });
  it("reports unsupported systems", () => { expect(getCaptureProtectionCapabilities("linux").captureProtectionSupported).toBe(false); expect(getCaptureProtectionCapabilities("win32", "10.0.17134").captureProtectionSupported).toBe(false); });
  it("requires native verification", () => { const manager = new CaptureProtectionManager({ capabilities: modern }); expect(manager.register("question", makeWindow()).health).toBe("FAILED"); });
  it("protects a verified window", () => { const manager = new CaptureProtectionManager({ capabilities: modern, verifyNativeAffinity: native() }); const window = makeWindow(); expect(manager.register("question", window).health).toBe("PROTECTED"); expect(window.setContentProtection).toHaveBeenCalledWith(true); });
  it("uses WDA_MONITOR on older Windows", () => { const manager = new CaptureProtectionManager({ capabilities: old, verifyNativeAffinity: native("WDA_MONITOR") }); expect(manager.register("answer", makeWindow()).health).toBe("PROTECTED"); });
  it("aggregates five overlay windows", () => { const manager = new CaptureProtectionManager({ capabilities: modern, scope: "overlays", verifyNativeAffinity: native() }); for (const panel of ["question", "answer", "script", "control", "transient"] as const) manager.register(panel, makeWindow()); expect(manager.state).toMatchObject({ health: "PROTECTED", fullyProtected: true, partiallyProtected: false }); expect(manager.state.windows).toHaveLength(5); });
  it("fails closed for one wrong affinity", () => { let calls = 0; const manager = new CaptureProtectionManager({ capabilities: modern, verifyNativeAffinity: () => ++calls === 2 ? { ok: true, affinity: 1, affinityName: "WDA_MONITOR" } : { ok: true, affinity: 0x11, affinityName: "WDA_EXCLUDEFROMCAPTURE" } }); const question = makeWindow(); const answer = makeWindow(); manager.register("question", question); const state = manager.register("answer", answer); expect(state).toMatchObject({ health: "PARTIALLY_PROTECTED", failClosed: true }); expect(question.hide).toHaveBeenCalled(); expect(answer.hide).toHaveBeenCalled(); });
  it("fails closed for a false Electron flag", () => { const manager = new CaptureProtectionManager({ capabilities: modern, verifyNativeAffinity: native() }); const window = makeWindow(false); expect(manager.register("control", window).health).toBe("FAILED"); expect(window.hide).toHaveBeenCalled(); });
  it("disables without fail closing", () => { const manager = new CaptureProtectionManager({ capabilities: modern, verifyNativeAffinity: native() }); const window = makeWindow(); manager.register("question", window); expect(manager.setRequested(false)).toMatchObject({ health: "DISABLED", failClosed: false, applied: false }); expect(window.setContentProtection).toHaveBeenLastCalledWith(false); });
  it("application scope includes main", () => { const manager = new CaptureProtectionManager({ capabilities: modern, scope: "application", verifyNativeAffinity: native() }); manager.register("main", makeWindow()); manager.register("question", makeWindow()); expect(manager.state.windows.map((item) => item.panel)).toEqual(["main", "question"]); });
  it("overlay scope excludes main", () => { const manager = new CaptureProtectionManager({ capabilities: modern, scope: "overlays", verifyNativeAffinity: native() }); manager.register("main", makeWindow()); manager.register("question", makeWindow()); expect(manager.state.windows.find((item) => item.panel === "main")?.requested).toBe(false); expect(manager.state.health).toBe("PROTECTED"); });
  it("records external modes separately", () => { const manager = new CaptureProtectionManager({ capabilities: modern, verifyNativeAffinity: native() }); manager.register("question", makeWindow()); manager.recordExternalVerification("window", true); expect(manager.recordExternalVerification("display", false)).toMatchObject({ windowCaptureVerified: true, displayCaptureVerified: false, externalCaptureVerified: false }); });
  it("keeps the compatibility helper", () => expect(applyCaptureProtection(makeWindow(), true, modern)).toMatchObject({ health: "PROTECTED", osFlagApplied: true }));
});
